%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0, 0, 1, 0]
    - [-1, 0, 0, 0]
    - [0, -1, 0, 0]
    - [0, 0, 0, 1]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [173.205078125, 173.205078125, 400, 300] #fu, fv, cu, cv
  resolution: [800, 600]
  rostopic: /uav/camera/left/image_rect_color