%YAML:1.0


acc_noise_density_multiplier: 1.0
gate_size: 1.6764
gate_map_path: "/home/nvidia/workspaces/fsc_ws/src/dome_circle.yaml"
engine_file_path: "/home/nvidia/workspaces/fsc_ws/src/gate_fusion/engine/dome_color.engine"
start_pos_offset: [0, 0.0, 0]
gate_match_threshold: 1.5
rpj_error_threshold: 10
time_offset: -0.00220

# imu and camera spacial-temporal
# imu config should also have the correct noise values
config_path_imu: "/home/nvidia/workspaces/fsc_ws/src/gate_fusion/config/orin16/imu_cam-imu.yaml"
config_path_imucam: "/home/nvidia/workspaces/fsc_ws/src/gate_fusion/config/orin16/imu_cam-camchain-imucam.yaml"