%YAML:1.0


acc_noise_density_multiplier: 1.0
gate_size: 1.7
gate_map_path: "/home/noidvan/workspaces/fg_ws/src/agihawk/racetracks/dome_circle.yaml"
engine_file_path: "/home/noidvan/workspaces/fg_ws/src/gate_fusion/engine/dome_pencil.engine"
start_pos_offset: [0, 0.0, 0]
gate_match_threshold: 1.0
rpj_error_threshold: 50

# imu and camera spacial-temporal
# imu config should also have the correct noise values
config_path_imu: "/home/noidvan/workspaces/fg_ws/src/gate_fusion/config/orin16/cam_imu-imu.yaml"
config_path_imucam: "/home/noidvan/workspaces/fg_ws/src/gate_fusion/config/orin16/cam_imu-camchain-imucam.yaml"